name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Get Python version
        id: python-version
        run: echo ::set-output name=version::"$(python -c "import sys; print('-'.join(str(v) for v in sys.version_info))")"

      - name: Run poetry image
        uses: abatilo/actions-poetry@v2.1.4
        with:
          poetry-version: "1.1.12"

      - name: Set poetry virtualenv
        run: poetry config virtualenvs.in-project true

      - name: Set up cache
        uses: actions/cache@v3
        id: cache
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.python-version.outputs.version }}-${{ hashFiles('poetry.lock') }}

      - name: Ensure cache is healthy
        if: steps.cache.outputs.cache-hit == 'true'
        shell: bash
        run: timeout 10s python -m poetry run pip --version || rm -rf .venv

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Lint flake8
        run: |
          poetry run pre-commit run --hook-stage manual flake8 --all-files --show-diff-on-failure

      - name: Check black
        run: |
          poetry run pre-commit run --hook-stage manual black --all-files --show-diff-on-failure

      - name: Check mypy
        run: |
          poetry run pre-commit run --hook-stage manual mypy --all-files

      - name: Update Python syntax
        run: |
          poetry run pre-commit run --hook-stage manual pyupgrade --all-files

      - name: Test pytest
        run: |
          poetry run pytest
