name: Publish

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          python-version: "3.12"
          version: latest

      - name: Build
        run: uv build

      - name: Publish TestPyPI
        run: uv publish --trusted-publishing always -r testpypi
        env:
          UV_PUBLISH_URL: https://test.pypi.org/legacy/

      - name: Publish PyPI
        run: uv publish --trusted-publishing always
