name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v4
        with:
          python-version: ${{ matrix.python-version }}
          version: latest

      - name: Check uv.lock
        run: uv run --frozen pre-commit run uv-lock-check --all-files

      - name: Lint (ruff)
        run: uv run --frozen ruff check . --config pyproject.toml --output-format=github --no-fix

      - name: Formatting (ruff)
        run: uv run --frozen pre-commit run ruff-format --all-files --show-diff-on-failure

      - name: Typing (pyright)
        run: uv run --frozen pre-commit run pyright --all-files

      - name: Test
        run: uv run --frozen pytest tests
