name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          version: latest

      - name: Check uv.lock
        run: uv lock --check

      - name: Lint (ruff)
        run: uv run --frozen ruff check . --config pyproject.toml --output-format=github --no-fix

      - name: Formatting (ruff)
        run: uv run --frozen ruff format

      - name: Typing (pyright)
        run: uv run --frozen pyright

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          version: latest

      - name: Test
        run: uv run --frozen pytest tests
